include $(MIROROS_ASP3_TOP_DIR)/Makefile.config

APPL_DIRS += $(MIROROS_ASP3_TOP_DIR)/micro_ros_asp
APPL_COBJS += micro_ros_asp.o

MICROROSLIB_DIR = external/$(BUILDTARGET)
MICROROS_LIB = $(MICROROSLIB_DIR)/firmware/build/
MICROROS_INC = $(MICROROSLIB_DIR)/firmware/build/include

INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/micro_ros_asp
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/action_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/actionlib_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/builtin_interfaces/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/composition_interfaces/i
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/diagnostic_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/example_interfaces/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/geometry_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/libyaml_vendor/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/lifecycle_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/micro_ros_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/micro_ros_utilities/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/microcdr/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/microxrcedds_client/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/nav_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcl/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcl_action/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcl_interfaces/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcl_lifecycle/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcl_logging_interface/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rclc/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rclc_lifecycle/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rclc_parameter/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rcutils/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rmw/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rmw_microxrcedds/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosgraph_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosidl_runtime_c/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosidl_typesupport_c/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosidl_typesupport_interface/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosidl_typesupport_introspection_c/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/rosidl_typesupport_microxrcedds_c/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/sensor_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/shape_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/statistics_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/std_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/std_srvs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/stereo_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/test_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/tracetools/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/trajectory_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/unique_identifier_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/visualization_msgs/
INCLUDES += -I$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_INC)/

LDFLAGS += -L$(MIROROS_ASP3_TOP_DIR)/$(MICROROS_LIB)/

LIBS += -lmicroros

