#
# 使用するターゲットボードのみ残してコメントアウトしてください
#

# Discovery F413ZH
#TARGET = discovery_f413xx_gcc
#MCU_WS = mcu_ws

# Nucleo F767ZI
# （トピックの登録は出来るが途中で止まってしまう）
#TARGET = nucleo_f767zi_gcc
#MCU_WS = mcu_ws_f767zi

# Prime Hub
TARGET = primehub_gcc
MCU_WS = mcu_ws
